# Generated by Django 4.2.7 on 2026-03-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(blank=True, max_length=200)),
                ("time", models.TimeField()),
                ("action", models.CharField(max_length=300)),
                ("is_pleasant", models.BooleanField(default=False)),
                ("frequency_days", models.PositiveSmallIntegerField(default=1)),
                ("reward", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "estimated_time_seconds",
                    models.PositiveSmallIntegerField(default=60),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("last_completed", models.DateTimeField(blank=True, null=True)),
                ("last_reminded", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_habits",
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
